version: '3'
services:
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9090:9090"
    volumes:
      - minio:/data
    environment:
      MINIO_ROOT_USER: $ROOT_USER
      MINIO_ROOT_PASSWORD: $ROOT_PASSWORD
    command: server /data --address :9000 --console-address :9090

  init-minio:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      mc config host add myminio http://minio:9000 $ROOT_USER $ROOT_PASSWORD;
      mc admin user add myminio $ACCESS_KEY_ID $SECRET_ACCESS_KEY;
      mc admin policy set myminio $USER_POLICY user=$ACCESS_KEY_ID;
      mc mb --ignore-existing myminio/$BUCKET_NAME;
      exit 0;
      "

volumes:
  minio:
